### ISSUE TITLE
Insegnamento `lab`

### ISSUE THREAD

**Issue by foxyseta** [csunibo/config#17]
Quest'anno i nostri laboratori fra pari si sono espansi anche alle matricole di Management, oltre che a quelle di Informatica. Statik già pubblica i relativi contenuti didattici da anno scorso: https://csunibo.github.io/lab/.

Per integrarli in dynamik, come li classifichiamo dentro `courses.json`? Non penso vada bene metterlo dentro a nessun CdL, perché idealmente vorremmo aprirli a tutto il dipartimento. Si potrebbe mettere un nuovo CdL e, al suo interno, "Tutti gli anni" o "Primo anno"? @csunibo/frontend 

Dopo attenta discussione su #20, lo schema risultante è il seguente:
https://github.com/csunibo/config/pull/20#issuecomment-1780893178

P.S.: dopo averli aggiunti a dynamik, bisognerà anche:

- [ ] usare il link dynamik nella pagina iniziale di CSUnibo con i vari progetti, anziché quello static;
- [ ] usare il link dynamik nella pagina relativa dentro alla wiki di CSUnibo, anziché quello static;

**Comment by ali-benny** [comment]
con @kocierik  avevamo pensato di fare un bottone dedicato nella home

**Comment by foxyseta** [comment]
Sisi quello c'è già, però linka a statik che è deprecato. Se vogliamo che linki a dynamik (che è supportato e sviluppato con tutte le funzionalità moderne fighe) dobbiamo aggiungerlo a courses.json e quindi compare pure in dynamik. A meno che non vogliate modificare dynamik apposta affinché lo nasconda. Cosa pensate sia meglio?

**Comment by ali-benny** [comment]
> Sisi quello c'è già, però linka a statik che è deprecato. 

Si, intendevo che volevamo aggiungerlo al `course.json` in modo tale che in dynamik fosse nella home, essendo materiale utile ed esterno ad ogni CdL.

> A meno che non vogliate modificare dynamik apposta affinché lo nasconda. Cosa pensate sia meglio?

Nono assolutamente, non avrebbe senso nasconderlo secondo me.

**Comment by foxyseta** [comment]
Quindi non volete fare CdL:"Laboratori fra pari"/Insegnamento:"lab"/(materiali della repo) ma direttamente CdL:"Laboratori fra pari"/(materiali della repo) giusto? (Per evitare inutili scatole cinesi.) Se sì, andrà modificato anche dynamik perché il pulsante ha un comportamento diverso rispetto aii "normali" CdL e possiamo aprire una issue anche là.

**Comment by ali-benny** [comment]
> Quindi non volete fare CdL:"Laboratori fra pari"/Insegnamento:"lab"/(materiali della repo) ma direttamente CdL:"Laboratori fra pari"/(materiali della repo) giusto? (Per evitare inutili scatole cinesi.) Se sì, andrà modificato anche dynamik perché il pulsante ha un comportamento diverso rispetto aii "normali" CdL e possiamo aprire una issue anche là.

Si beh, sarebbe carino evitare!! Oks per l'issue.

**Comment by VaiTon** [comment]
Vedi https://github.com/csunibo/dynamik/issues/122#issuecomment-1772557689 per proposte di come ri-strutturare il/i file/s

**Comment by ali-benny** [comment]
domanda: `teachings.json` vogliamo strutturarlo in base agli anni o in base all'id [CdL]?
