### ISSUE TITLE
typo in `maintainers.json` filename

### ISSUE THREAD

**Issue by foxyseta** [csunibo/config#55]
`mantainers.json` should be `maintainers.json`. @Jabbar03 I believe this feature was implemented by you. Could you maybe rename it and update the corresponding code at Informabot?

**Comment by foxyseta** [comment]
While you are at it, I believe this file is not documented in our wiki, unlike the rest of this repository:
https://github.com/csunibo/csunibo.github.io/blob/main/content/it/wiki/infrastruttura/configurazioni.md
https://github.com/csunibo/csunibo.github.io/blob/main/content/en/wiki/infrastruttura/configurazioni.md

**Comment by foxyseta** [comment]
@Jabbar03 hai aggiornato anche lato Informabot?

**Comment by Jabbar03** [comment]
giusto, lato wiki lo faccio subito, per quanto bot dici che devo riaggiornare i sottomoduli ?

**Comment by Jabbar03** [comment]
forse c'è un typo anche nel bot, adesso fixo anche lì

**Comment by foxyseta** [comment]
Sì intendevo che il bot sicuramente sta chiamando questo file da qualche parte ancora con il nome sbagliato. In più, è possibile (non certo) che abbia anche alcune variabili con lo stesso refuso.

**Comment by samuelemusiani** [comment]
Chiuse tutte le pr relative

**Comment by foxyseta** [comment]
In Informabot oltre al sottomodulo è stato aggiornato anche il sorgente?

**Comment by samuelemusiani** [comment]
Si
