### ISSUE TITLE
Visualizzazione di file AsciiDoc

### ISSUE THREAD

**Issue by VaiTon** [csunibo/config#65]
### Implementazione

~C'è questa lib su NPM, che è derivata da asciidoctor (in ruby), convertita in js via Opal: https://github.com/asciidoctor/asciidoctor.js~

~Visto che il bundle size è molto alto (> 1MB) è necessario importarlo solo se necessario, ed eventualmente fare l'operazione di rendering nella load, in modo da farla fare al server quando disponibile.~

Abbiamo deciso inizialmente di provare a compilare gli asciidoc in html e caricare quelli dal client.

### Tasks
- [x] https://github.com/csunibo/build-image/issues/1

**Comment by foxyseta** [comment]
Moved to #64.
