### ISSUE TITLE
Insegnamenti di Informatica per il management

### ISSUE THREAD

**Issue by foxyseta** [csunibo/config#7]
Molti informatici scelgono come insegnamenti opzionali alcuni di informatica per il management, e molti informatici per il management seguono come insegnmenti opzionali quelli di informatica. Inoltre Tecnologie web di Informatica (9 CFU) e di Informatica per il management (6 CFU) condividono molte slide e lezioni con gli stessi professori.
Sarebbe utile aggiungere a https://risorse.students.cs.unibo.it gli altri insegnamenti di Informatica per il management, e riclassificare eventuali insegnamenti già classificati sotto informatica come di informatica per il management.

Aggiungere gli insegnamenti è facilissimo: basta seguire la pagina Wiki appropriata: https://csunibo.github.io/wiki/raccolte-di-risorse/aggiungere-un-nuovo-insegnamento/index.html

Ha senso effettuare questa operazione solo quando si ha la certezza di avere persone volontarie disposte ad approvare PR e a caricare materiale.

**Comment by ali-benny** [comment]
#37 #36 close this
