### ISSUE TITLE
Artificial Intelligence MSc Teachings

### ISSUE THREAD

**Issue by Flecart** [csunibo/config#8]
Wouldn't it be cool to feature the teachings from the Artificial Intelligence MSc too?

- [x] translate CSUnibo's home page
- [x] contact the AI students' representative (he's okay with this)
- [ ] add material (let @angelogalav and the other volunteeers do some of this, as to show them the process):
  - [ ] https://github.com/montali/unibo-ai
  - [ ] https://github.com/MatteoDonati/unibo_artificial_intelligence_notes
  - [x] https://github.com/AngeloGalav/deep-learning-notes
  - [ ] https://github.com/AngeloGalav/MachineLearningNotes
  - [ ] https://github.com/AngeloGalav/ComputerGraphicsNotes
  - [ ] https://github.com/AngeloGalav/ComputerNetworksNotes
  - [ ] https://github.com/AngeloGalav/CybersecurityLab
  - [ ] https://liveunibo-my.sharepoint.com/:f:/g/personal/andrea_terenziani_studio_unibo_it/EhFT6PXuD5BLiH-sylLPG8UBTxB8mUV9T8ir8Fb9hTh95w?e=MYYfui
- [x] add [groupchats links](https://linktr.ee/MasterAI_21_22) to [config](https://github.com/csunibo/config)

**Comment by foxyseta** [comment]
@angelogalav provided a list of this repositories concerning AI teachings. For each of those, he is letting us not only link them from CSUnibo but also upload his material directly to our repos (which has not been created yet).

The big idea is to first upload this material to gain appeal for AI students. In the meantime, we are also working on a bilingual CSUnibo hompage. Finally, we can get back to the newly elected student representative (Alberto Luise) and give this another try.

**Comment by Flecart** [comment]
Hi @foxyseta, i tried to add the Galav Deep learning notes, but don't know how to quickly rename (or don't check the names) of the image folder, so the build fails.
Check here: https://github.com/csunibo/deep-learning/pull/1 

The default site with just the slides works.

**Comment by foxyseta** [comment]
Got back to you directly in the PR you mentioned: https://github.com/csunibo/deep-learning/pull/1#issuecomment-1772454857.

**Comment by AngeloGalav** [comment]
> Hi @foxyseta, i tried to add the Galav Deep learning notes, but don't know how to quickly rename (or don't check the names) of the image folder, so the build fails. Check here: [csunibo/deep-learning#1](https://github.com/csunibo/deep-learning/pull/1)
> 
> The default site with just the slides works.

Btw I can convert those notes in pdf format if you prefer, and then you would simply upload the pdf file

**Comment by foxyseta** [comment]
No need for that, thanks! As specified in https://csunibo.github.io/wiki/raccolte-di-risorse/index.html, MDs are actually even more welcomed than PDFs.

**Comment by foxyseta** [comment]
Created branch `feat/ai` to add AI teachings. @csunibo/artificial-intelligence @csunibo/informatica we now need volunteers to:
- [ ] create the missing repositories (https://csunibo.github.io/wiki/raccolte-di-risorse/aggiungere-un-nuovo-insegnamento/) using these [groupchat links](https://linktr.ee/MasterAI_21_22) when editing `csunibo/config`
- [ ] add materials [listed here](https://github.com/csunibo/config/issues/8#issue-1925811288) to said repositories.

Anybody up for this job?

**Comment by foxyseta** [comment]
Created the repositories: a67994652eb382b194a95a747aa375b328a1f4da and 1407ef2ea4fc8081379b94896b1ac8bd81da9ecf. Closing this issue as adding materials is unrelated to `src/config`. We should still do it nontheless.
